# accept keywords as regex??

[special.functions]
main = "kunsa"
print = "imprimir"

[keywords.control_flow_keywords]
if_statement_keyword = "si"
else_statement_keyword = "se_não"
for_loop_keyword = "pa"
while_loop_keyword = "enquanto"
break_keyword = "para" 
continue_keyword = "salta" 


[keywords.declarator_keywords]
function_declaration_keyword = "tarbadju"
return_keyword = "tornal"
assignment_keyword = "si_bu_odja"


[keywords.datatypes]
int_primitive_keyword = "int"
f32_primitive_keyword = "f32"
f64_primitive_keyword = "f64"
bool_primitive_keyword = "bool"
char_primitive_keyword = "char"
str_primitive_keyword = "str"


[regex.booleans]
boolean_true = "bardadi"
boolean_false = "mintida"
